### ISSUE TITLE
Color Glow.

### ISSUE THREAD

**Issue by Dmp13** [GDKID69/gdkord#1]
I think a great feature to add to your theme is a color glow picker for people who want to change the pink glow to another color

**Comment by fuh-Q** [comment]
You were always able to change the colour, it just wasn't clear how to do it. I've re-structured `:root` up at the top and added some comments to hopefully make things easier, just re-open your command terminal in this theme's folder and run
`git pull` to apply the changes, **the new values you set must remain in RGB form though**

You can use [this tool](https://g.co/kgs/bHhn6p) to pick a colour you like and to get the RGB value

![image](https://user-images.githubusercontent.com/77850955/139501687-71fb4395-69bb-45b8-99c7-a711225e9327.png)
